spring:
  application:
    name: jpa-aux-table
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test
    username: root
    password: mdymen_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # This line creates and drops tables on app run
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

#jakarta:
#  persistence:
#    jdbc:
#      url: jdbc:mysql://localhost:3306/jpa_test
#      user: root
#      password: mdymen_pass
#
#hibernate:
#  dialect: org.hibernate.dialect.MySQLDialect
